/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HunterRouteImport } from './routes/hunter'
import { Route as EngineRouteImport } from './routes/engine'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HunterIndexRouteImport } from './routes/hunter.index'
import { Route as HunterManualRouteImport } from './routes/hunter.manual'
import { Route as DemoAgency2RouteImport } from './routes/demo.agency2'
import { Route as DemoAgencyRouteImport } from './routes/demo.agency'
import { Route as ApiPublicVeritaSubscribeRouteImport } from './routes/api/public/verita-subscribe'

const HunterRoute = HunterRouteImport.update({
  id: '/hunter',
  path: '/hunter',
  getParentRoute: () => rootRouteImport,
} as any)
const EngineRoute = EngineRouteImport.update({
  id: '/engine',
  path: '/engine',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HunterIndexRoute = HunterIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HunterRoute,
} as any)
const HunterManualRoute = HunterManualRouteImport.update({
  id: '/manual',
  path: '/manual',
  getParentRoute: () => HunterRoute,
} as any)
const DemoAgency2Route = DemoAgency2RouteImport.update({
  id: '/demo/agency2',
  path: '/demo/agency2',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoAgencyRoute = DemoAgencyRouteImport.update({
  id: '/demo/agency',
  path: '/demo/agency',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicVeritaSubscribeRoute =
  ApiPublicVeritaSubscribeRouteImport.update({
    id: '/api/public/verita-subscribe',
    path: '/api/public/verita-subscribe',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/engine': typeof EngineRoute
  '/hunter': typeof HunterRouteWithChildren
  '/demo/agency': typeof DemoAgencyRoute
  '/demo/agency2': typeof DemoAgency2Route
  '/hunter/manual': typeof HunterManualRoute
  '/hunter/': typeof HunterIndexRoute
  '/api/public/verita-subscribe': typeof ApiPublicVeritaSubscribeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/engine': typeof EngineRoute
  '/demo/agency': typeof DemoAgencyRoute
  '/demo/agency2': typeof DemoAgency2Route
  '/hunter/manual': typeof HunterManualRoute
  '/hunter': typeof HunterIndexRoute
  '/api/public/verita-subscribe': typeof ApiPublicVeritaSubscribeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/engine': typeof EngineRoute
  '/hunter': typeof HunterRouteWithChildren
  '/demo/agency': typeof DemoAgencyRoute
  '/demo/agency2': typeof DemoAgency2Route
  '/hunter/manual': typeof HunterManualRoute
  '/hunter/': typeof HunterIndexRoute
  '/api/public/verita-subscribe': typeof ApiPublicVeritaSubscribeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/engine'
    | '/hunter'
    | '/demo/agency'
    | '/demo/agency2'
    | '/hunter/manual'
    | '/hunter/'
    | '/api/public/verita-subscribe'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/engine'
    | '/demo/agency'
    | '/demo/agency2'
    | '/hunter/manual'
    | '/hunter'
    | '/api/public/verita-subscribe'
  id:
    | '__root__'
    | '/'
    | '/engine'
    | '/hunter'
    | '/demo/agency'
    | '/demo/agency2'
    | '/hunter/manual'
    | '/hunter/'
    | '/api/public/verita-subscribe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EngineRoute: typeof EngineRoute
  HunterRoute: typeof HunterRouteWithChildren
  DemoAgencyRoute: typeof DemoAgencyRoute
  DemoAgency2Route: typeof DemoAgency2Route
  ApiPublicVeritaSubscribeRoute: typeof ApiPublicVeritaSubscribeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/hunter': {
      id: '/hunter'
      path: '/hunter'
      fullPath: '/hunter'
      preLoaderRoute: typeof HunterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engine': {
      id: '/engine'
      path: '/engine'
      fullPath: '/engine'
      preLoaderRoute: typeof EngineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hunter/': {
      id: '/hunter/'
      path: '/'
      fullPath: '/hunter/'
      preLoaderRoute: typeof HunterIndexRouteImport
      parentRoute: typeof HunterRoute
    }
    '/hunter/manual': {
      id: '/hunter/manual'
      path: '/manual'
      fullPath: '/hunter/manual'
      preLoaderRoute: typeof HunterManualRouteImport
      parentRoute: typeof HunterRoute
    }
    '/demo/agency2': {
      id: '/demo/agency2'
      path: '/demo/agency2'
      fullPath: '/demo/agency2'
      preLoaderRoute: typeof DemoAgency2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/agency': {
      id: '/demo/agency'
      path: '/demo/agency'
      fullPath: '/demo/agency'
      preLoaderRoute: typeof DemoAgencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/verita-subscribe': {
      id: '/api/public/verita-subscribe'
      path: '/api/public/verita-subscribe'
      fullPath: '/api/public/verita-subscribe'
      preLoaderRoute: typeof ApiPublicVeritaSubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface HunterRouteChildren {
  HunterManualRoute: typeof HunterManualRoute
  HunterIndexRoute: typeof HunterIndexRoute
}

const HunterRouteChildren: HunterRouteChildren = {
  HunterManualRoute: HunterManualRoute,
  HunterIndexRoute: HunterIndexRoute,
}

const HunterRouteWithChildren =
  HunterRoute._addFileChildren(HunterRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EngineRoute: EngineRoute,
  HunterRoute: HunterRouteWithChildren,
  DemoAgencyRoute: DemoAgencyRoute,
  DemoAgency2Route: DemoAgency2Route,
  ApiPublicVeritaSubscribeRoute: ApiPublicVeritaSubscribeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
