/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EngineRouteImport } from './routes/engine'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoAgency2RouteImport } from './routes/demo.agency2'
import { Route as DemoAgencyRouteImport } from './routes/demo.agency'

const EngineRoute = EngineRouteImport.update({
  id: '/engine',
  path: '/engine',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoAgency2Route = DemoAgency2RouteImport.update({
  id: '/demo/agency2',
  path: '/demo/agency2',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoAgencyRoute = DemoAgencyRouteImport.update({
  id: '/demo/agency',
  path: '/demo/agency',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/engine': typeof EngineRoute
  '/demo/agency': typeof DemoAgencyRoute
  '/demo/agency2': typeof DemoAgency2Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/engine': typeof EngineRoute
  '/demo/agency': typeof DemoAgencyRoute
  '/demo/agency2': typeof DemoAgency2Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/engine': typeof EngineRoute
  '/demo/agency': typeof DemoAgencyRoute
  '/demo/agency2': typeof DemoAgency2Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/engine' | '/demo/agency' | '/demo/agency2'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/engine' | '/demo/agency' | '/demo/agency2'
  id: '__root__' | '/' | '/engine' | '/demo/agency' | '/demo/agency2'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EngineRoute: typeof EngineRoute
  DemoAgencyRoute: typeof DemoAgencyRoute
  DemoAgency2Route: typeof DemoAgency2Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/engine': {
      id: '/engine'
      path: '/engine'
      fullPath: '/engine'
      preLoaderRoute: typeof EngineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/agency2': {
      id: '/demo/agency2'
      path: '/demo/agency2'
      fullPath: '/demo/agency2'
      preLoaderRoute: typeof DemoAgency2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/agency': {
      id: '/demo/agency'
      path: '/demo/agency'
      fullPath: '/demo/agency'
      preLoaderRoute: typeof DemoAgencyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EngineRoute: EngineRoute,
  DemoAgencyRoute: DemoAgencyRoute,
  DemoAgency2Route: DemoAgency2Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
