/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoAgency2RouteImport } from './routes/demo.agency2'
import { Route as DemoAgencyRouteImport } from './routes/demo.agency'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoAgency2Route = DemoAgency2RouteImport.update({
  id: '/demo/agency2',
  path: '/demo/agency2',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoAgencyRoute = DemoAgencyRouteImport.update({
  id: '/demo/agency',
  path: '/demo/agency',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo/agency': typeof DemoAgencyRoute
  '/demo/agency2': typeof DemoAgency2Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo/agency': typeof DemoAgencyRoute
  '/demo/agency2': typeof DemoAgency2Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demo/agency': typeof DemoAgencyRoute
  '/demo/agency2': typeof DemoAgency2Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/demo/agency' | '/demo/agency2'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/demo/agency' | '/demo/agency2'
  id: '__root__' | '/' | '/demo/agency' | '/demo/agency2'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoAgencyRoute: typeof DemoAgencyRoute
  DemoAgency2Route: typeof DemoAgency2Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/agency2': {
      id: '/demo/agency2'
      path: '/demo/agency2'
      fullPath: '/demo/agency2'
      preLoaderRoute: typeof DemoAgency2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/agency': {
      id: '/demo/agency'
      path: '/demo/agency'
      fullPath: '/demo/agency'
      preLoaderRoute: typeof DemoAgencyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoAgencyRoute: DemoAgencyRoute,
  DemoAgency2Route: DemoAgency2Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
